export const GET_POSTS_CATEGORY = 'GET_POSTS_CATEGORY';
export const GET_POSTS_SUBREDDIT = 'GET_POSTS_SUBREDDIT';
export const SET_SLIDESHOW_VISIBILITY = 'SET_SLIDESHOW_VISIBILITY';
export const SET_SLIDESHOW_IMAGE = 'SET_SLIDESHOW_IMAGE';
export const GET_LIST = 'GET_LIST';
export const SET_LANDING_TOGGLE = 'SET_LANDING_TOGGLE';
