const subredditList = {
  art: [
    'ImaginaryTechnology',
    'ImaginaryMaps',
    'ImaginaryNobles',
    'ImaginaryWitches',
    'ImaginaryAngels',
    'ImaginaryElves',
    'ImaginaryFaeries',
    'ImaginaryCityscapes',
    'ImaginaryArchitecture',
    'ImaginaryCastles',
    'ImaginaryDwellings',
    'ImaginaryInteriors',
    'ImaginaryLibraries',
    'MtgPorn',
  ],
  animals: [
    'AnimalsBeingBros',
    'AnimalsBeingDerps',
    'Aww',
    'BabyWildAnimals',
    'NatureIsFuckingLit',
    'NatureIsMetal',
    'CatPics',
    'BabyElephantGifs',
    'CatsStandingUp',
  ],
  nature: [
    'EarthPorn',
    'HeavySeas',
    'Succulents',
    'Bonsai',
    'ChemicalReactionGifs',
    'AerialPorn',
    'RuralPorn',
    'WinterPorn',
    'SpacePorn',
    'WaterPorn',
    'SkyPorn',
    'GeologyPorn',
  ],
  food: [
    'TonightsDinner',
    'DessertPorn',
    'Charcuterie',
    'KoreanFood',
    'Breadit',
    'Pizza',
    'GrilledCheese',
    'Food',
  ],
  manMade: [
    'SteamPorn',
    'CarPorn',
    'ArtefactPorn',
    'ThingsCutInHalfPorn',
    'RoomPorn',
    'StarshipPorn',
    'AbandonedPorn',
    'DesignPorn',
    'OrganizationPorn',
    'ArchitecturePorn',
    'CabinPorn',
    'CozyPlaces',
  ],
};

module.exports = { subredditList };
